config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => 'users/registrations' }

  root :to => "home#about_whyjustrun"
  get 'pages/privacy_policy', to: 'pages#privacy_policy'
  get 'about/orienteering', to: 'home#about_orienteering'
  get 'events/calendar', to: 'events#calendar'
  get 'clubs/map', to: 'clubs#map'
  get 'users/sign_in_clubsite', to: 'users#sign_in_clubsite'
  get 'users/sign_out_clubsite', to: 'users#sign_out_clubsite'
  # must be an integer
  user_id_constraint = { :user_id => /\b\d+\b/ }
  get 'users/:user_id', to: 'users#show', :constraints => user_id_constraint, :as => :user
  put 'users/:user_id', to: 'users#send_message', :constraints => user_id_constraint

  # :iof_version => /[^\/]*/ is needed to allow dots in the IOF XML version #
  version_constraint = { :iof_version => /[^\/]*/ }
  get 'iof/:iof_version/events/:id/start_list', to: 'events#start_list', :constraints => version_constraint
  get 'iof/:iof_version/organization_list', to: 'clubs#index', :constraints => version_constraint
  get 'iof/:iof_version/competitor_list', to: 'users#competitor_list', :constraints => version_constraint
  get 'iof/:iof_version/events/:id/entry_list', to: 'events#entry_list', :constraints => version_constraint

  get 'iof/:iof_version/users/event_list/limit/:limit', to: 'events#event_list_for_user', :constraints => version_constraint
  get 'iof/:iof_version/users/event_list', to: 'events#event_list_for_user', :constraints => version_constraint

  get 'iof/:iof_version/clubs/:club_id/event_list', to: 'events#index', :constraints => version_constraint

  # TODO TMP
  get 'iof/result_list', to: 'results#update_result_list'
  get 'iof/:iof_version/events/:id/result_list', to: 'results#result_list', :constraints => version_constraint
  post 'iof/:iof_version/events/:id/result_list', to: 'results#process_result_list', :constraints => version_constraint
  post 'iof/:iof_version/events/:id/live_result_list', to: 'results#update_live_result_list', :constraints => version_constraint
  get 'iof/:iof_version/events/:id/live_result_list', to: 'results#live_result_list', :constraints => version_constraint

  get 'events', to: 'events#index', format: true
  get 'club/:club_id/events', to: 'events#index', format: true
  get 'club/:club_id/participation_report', to: 'clubs#participant_counts'
  get 'clubsite/:club_id', to: 'clubs#show_clubsite', as: :clubsite

  get 'api/maps', to: 'maps#index'

  post 'api/redactor/uploadImage', to: 'redactor#upload_image'
  post 'api/redactor/uploadFile', to: 'redactor#upload_file'

  # Handle all CORS OPTIONS requests
  match '*all', to: 'application#cors', via: [:options]
  
  get ':name', to: 'short_links#show'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "WhyJustRun" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
    <div class="navbar navbar-fixed-top navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#wjr-navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href=<%= root_path %>>WhyJustRun</a>
        </div> 
        <div class="collapse navbar-collapse" id="wjr-navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "About Orienteering", about_orienteering_path  %></li>
            <li><%= link_to "Clubs", clubs_map_path  %></li>
            <li><%= link_to "Events", events_calendar_path  %></li>
            <% if user_signed_in? then %>
              <li><%= link_to "My Profile", user_path(current_user.id) %>
              <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
            <% else %>
              <li><%= link_to "Sign in", new_user_session_path %></li>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
            <% end %>
          </ul>
          <div class="navbar-right navbar-like-button">
            <div class="fb-like" data-href="https://www.facebook.com/WhyJustRunApp" data-layout="button_count" data-action="like" data-show-faces="true"></div>
          </div>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <div class="container">
      <%= bootstrap_flash %>
      <%= yield %>

      <footer>
      <p>&copy; WhyJustRun <%= Time.now.year %>
      | <%= link_to "Privacy Policy", pages_privacy_policy_path %>
      <span class="pull-right">
        By <a href="http://www.russellporter.com">Russell Porter</a> and Thomas Nipen | <a href="mailto:support@whyjustrun.ca">support@whyjustrun.ca</a>
      </span>
      </p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <script type="text/javascript">
      <%= yield :javascript %>
    </script>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=520486301348620";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
  </body>
</html>